# Generated by Django 5.0.6 on 2024-06-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='favorites',
            field=models.IntegerField(default=0),
        ),
    ]
