# Generated by Django 5.0.6 on 2024-06-19 22:43

from django.db import migrations

def set_default_user(apps, schema_editor):
    Comment = apps.get_model('personal', 'Comment')
    User = apps.get_model('auth', 'User')
    admin_user = User.objects.get(username='admin')
    
    for comment in Comment.objects.all():
        if comment.user_id is None:
            comment.user = admin_user
            comment.save()

class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_comment_user_alter_comment_name'),
    ]

    operations = [
    ]
