# Generated by Django 5.0.6 on 2024-06-20 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_auto_20240619_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('delete_own_comment', 'can delete only own comments')]},
        ),
    ]
