# Generated by Django 5.0.6 on 2024-06-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
