# Generated by Django 5.0.6 on 2024-06-20 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_bitacora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora',
            options={},
        ),
        migrations.RenameField(
            model_name='bitacora',
            old_name='verb',
            new_name='action',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='target_ct',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='target_id',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
