# Generated by Django 5.0.6 on 2024-06-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0013_alter_bitacora_options_rename_verb_bitacora_action_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bitacora',
        ),
    ]
